services:
  # app:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - .:/app
  #     - ./tsconfig.json:/app/tsconfig.json
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root